/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fff8ef',
        'surface-dim': '#e0d9cb',
        'surface-bright': '#fff8ef',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf3e4',
        'surface-container': '#f5edde',
        'surface-container-high': '#efe7d9',
        'surface-container-highest': '#e9e2d3',
        'on-surface': '#1e1b13',
        'on-surface-variant': '#45483f',
        'inverse-surface': '#343027',
        'inverse-on-surface': '#f8f0e1',
        'outline': '#75786e',
        'outline-variant': '#c5c8bc',
        'surface-tint': '#546345',
        'primary': '#536143',
        'on-primary': '#ffffff',
        'primary-container': '#6b7a5a',
        'on-primary-container': '#fcfff1',
        'inverse-primary': '#bccca7',
        'secondary': '#855324',
        'on-secondary': '#ffffff',
        'secondary-container': '#febb84',
        'on-secondary-container': '#79491b',
        'tertiary': '#506148',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#697a5f',
        'on-tertiary-container': '#fbfff2',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e8c2',
        'primary-fixed-dim': '#bccca7',
        'on-primary-fixed': '#131f07',
        'on-primary-fixed-variant': '#3d4b2f',
        'secondary-fixed': '#ffdcc2',
        'secondary-fixed-dim': '#fbb981',
        'on-secondary-fixed': '#2e1500',
        'on-secondary-fixed-variant': '#693c0f',
        'tertiary-fixed': '#d5e8c8',
        'tertiary-fixed-dim': '#b9ccad',
        'on-tertiary-fixed': '#111f0b',
        'on-tertiary-fixed-variant': '#3b4b33',
        'background': '#fff8ef',
        'on-background': '#1e1b13',
        'surface-variant': '#e9e2d3',
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
      },
      boxShadow: {
        'botanical': '0 20px 40px -15px rgba(58, 74, 50, 0.12)',
        'lift': '0 14px 28px rgba(83, 97, 67, 0.15)',
      }
    },
  },
  plugins: [],
}
